#pragma once

#include <QString>

#include <cstdint>
#include <functional>

extern "C" {
struct AVCodecParameters;
struct AVCodecContext;
struct AVPacket;
struct AVFrame;
struct AVFilterGraph;
struct AVFilterContext;
struct AVAudioFifo;
}

namespace harpia {

// Decodes a clip's audio, time-stretches each cut by its playback speed with
// FFmpeg's pitch-preserving atempo filter, and re-encodes the result as one
// continuous AAC track, handing packets to the caller's muxer via a callback.
// Output timestamps are generated by counting emitted samples, so consecutive
// cuts are gapless and stay aligned with the video's accumulated timeline.
//
// Usage per export: init() once, then for each cut beginSegment() → push()
// every source audio packet read in that cut's window → endSegment(); after the
// last cut call finish(). All methods return false with *err set on failure.
class AudioRetimer {
public:
	using WritePacket = std::function<bool(AVPacket *)>; // encoded AAC; pts in 1/sampleRate

	AudioRetimer() = default;
	~AudioRetimer();

	AudioRetimer(const AudioRetimer &) = delete;
	AudioRetimer &operator=(const AudioRetimer &) = delete;

	// srcPar + tbNum/tbDen: the source audio stream's codec parameters and time
	// base. globalHeader: true when the output container needs
	// AV_CODEC_FLAG_GLOBAL_HEADER on the encoder.
	bool init(const AVCodecParameters *srcPar, int tbNum, int tbDen, bool globalHeader, QString *err);

	// Valid after init(); used to create the muxer's audio stream.
	AVCodecContext *encoder() const { return enc_; }
	int sampleRate() const;

	bool beginSegment(int64_t startMs, int64_t endMs, double speed, QString *err);
	bool push(const AVPacket *pkt, const WritePacket &write, QString *err);
	bool endSegment(const WritePacket &write, QString *err);
	bool finish(const WritePacket &write, QString *err);

private:
	bool buildGraph(double speed, QString *err);
	void destroyGraph();
	bool drainSink(const WritePacket &write, QString *err); // filter → fifo → encoder
	bool encodeReady(const WritePacket &write, QString *err); // full frames from the fifo
	bool sendToEncoder(AVFrame *frame, const WritePacket &write, QString *err);

	AVCodecContext *dec_ = nullptr;
	AVCodecContext *enc_ = nullptr;
	AVFilterGraph *graph_ = nullptr;
	AVFilterContext *bufSrc_ = nullptr;
	AVFilterContext *bufSink_ = nullptr;
	AVAudioFifo *fifo_ = nullptr;
	AVFrame *decFrame_ = nullptr;
	AVFrame *filtFrame_ = nullptr;
	AVFrame *encFrame_ = nullptr;
	AVPacket *encPkt_ = nullptr;

	int tbNum_ = 1, tbDen_ = 1000; // source stream time base
	int64_t segStartTb_ = 0, segEndTb_ = 0;
	int64_t nextPts_ = 0; // samples emitted so far == next frame's pts
	bool inSegment_ = false;
};

} // namespace harpia
